package com.torve.desktop.ui.v2.discovery

enum class ContentDiscoveryType {
    TvShows,
    Movies,
    Mixed,
    LiveTv,
    Anime,
}

data class DiscoveryFilterConfig(
    val contentType: ContentDiscoveryType,
    val searchPlaceholder: String,
    val showAiSearch: Boolean,
    val showGeminiReady: Boolean,
    val showProviderFilter: Boolean,
    val providerLabel: String,
    val showNetworkFilter: Boolean,
    val showStudioFilter: Boolean,
    val showYearFilter: Boolean,
    val showRuntimeFilter: Boolean,
    val showStatusFilter: Boolean,
    val showRatingFilter: Boolean,
    val showLanguageFilter: Boolean,
    val showGenreChips: Boolean,
    val showMoodChips: Boolean,
    val showSortFilter: Boolean,
    val showReset: Boolean,
)

fun tvDiscoveryFilterConfig(
    providerAvailable: Boolean,
    networkAvailable: Boolean,
    aiAvailable: Boolean,
    geminiReadyAvailable: Boolean,
    showYear: Boolean = true,
    showStatus: Boolean = true,
    showRuntime: Boolean = false,
    showRating: Boolean = true,
    showLanguage: Boolean = false,
): DiscoveryFilterConfig = DiscoveryFilterConfig(
    contentType = ContentDiscoveryType.TvShows,
    searchPlaceholder = "Search shows, genres, people, moods",
    showAiSearch = aiAvailable,
    showGeminiReady = geminiReadyAvailable,
    showProviderFilter = providerAvailable,
    providerLabel = "Provider",
    showNetworkFilter = networkAvailable,
    showStudioFilter = false,
    showYearFilter = showYear,
    showRuntimeFilter = showRuntime,
    showStatusFilter = showStatus,
    showRatingFilter = showRating,
    showLanguageFilter = showLanguage,
    showGenreChips = true,
    showMoodChips = true,
    showSortFilter = true,
    showReset = true,
)

fun movieDiscoveryFilterConfig(
    aiAvailable: Boolean,
    geminiReadyAvailable: Boolean,
    showYear: Boolean = true,
    showRuntime: Boolean = true,
    showRating: Boolean = true,
    showLanguage: Boolean = true,
): DiscoveryFilterConfig = DiscoveryFilterConfig(
    contentType = ContentDiscoveryType.Movies,
    searchPlaceholder = "Search movies, actors, directors, moods",
    showAiSearch = aiAvailable,
    showGeminiReady = geminiReadyAvailable,
    showProviderFilter = false,
    providerLabel = "Provider",
    showNetworkFilter = false,
    showStudioFilter = false,
    showYearFilter = showYear,
    showRuntimeFilter = showRuntime,
    showStatusFilter = false,
    showRatingFilter = showRating,
    showLanguageFilter = showLanguage,
    showGenreChips = true,
    showMoodChips = true,
    showSortFilter = true,
    showReset = true,
)

fun mixedDiscoveryFilterConfig(
    aiAvailable: Boolean,
    geminiReadyAvailable: Boolean,
    showYear: Boolean = true,
): DiscoveryFilterConfig = DiscoveryFilterConfig(
    contentType = ContentDiscoveryType.Mixed,
    searchPlaceholder = "Search titles, genres, people, moods",
    showAiSearch = aiAvailable,
    showGeminiReady = geminiReadyAvailable,
    showProviderFilter = false,
    providerLabel = "Provider",
    showNetworkFilter = false,
    showStudioFilter = false,
    showYearFilter = showYear,
    showRuntimeFilter = false,
    showStatusFilter = false,
    showRatingFilter = false,
    showLanguageFilter = false,
    showGenreChips = true,
    showMoodChips = true,
    showSortFilter = true,
    showReset = true,
)

