#!/usr/bin/env python3
"""Legal Torve *Arr E2E fixture: Torznab feed, torrent file and HTTP tracker."""

from __future__ import annotations

import argparse
import hashlib
import os
import socket
import struct
import threading
import time
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import quote, unquote_to_bytes, urlsplit


PIECE_LENGTH = 256 * 1024
ANNOUNCE_URL = "http://fixture:8080/announce"
TORRENT_NAME = "Big.Buck.Bunny.2008.1080p.WEB-DL.x264.REPACK-TORVE-E2E.mkv"
# Keep the generated bytes clearly identified inside the file, while giving
# Radarr a parseable CC-movie release title so its normal decision pipeline
# can associate the legal fixture with the seeded library entry.
RELEASE_TITLE = "Big Buck Bunny 2008 1080p WEB-DL x264 REPACK-TORVE-E2E"


def bencode(value):
    if isinstance(value, bool):
        value = int(value)
    if isinstance(value, int):
        return b"i" + str(value).encode("ascii") + b"e"
    if isinstance(value, str):
        value = value.encode("utf-8")
    if isinstance(value, bytes):
        return str(len(value)).encode("ascii") + b":" + value
    if isinstance(value, list):
        return b"l" + b"".join(bencode(item) for item in value) + b"e"
    if isinstance(value, dict):
        encoded = []
        for key in sorted(value, key=lambda item: item.encode("utf-8") if isinstance(item, str) else item):
            encoded.append(bencode(key))
            encoded.append(bencode(value[key]))
        return b"d" + b"".join(encoded) + b"e"
    raise TypeError(f"Unsupported bencode type: {type(value)!r}")


def build_torrent(media_path: Path, torrent_path: Path) -> bytes:
    pieces = bytearray()
    with media_path.open("rb") as media:
        while chunk := media.read(PIECE_LENGTH):
            pieces.extend(hashlib.sha1(chunk).digest())
    info = {
        "length": media_path.stat().st_size,
        "name": media_path.name,
        "piece length": PIECE_LENGTH,
        "pieces": bytes(pieces),
    }
    payload = {
        "announce": ANNOUNCE_URL,
        "created by": "Torve legal E2E fixture",
        "creation date": int(time.time()),
        "comment": "Generated color bars and tone; no third-party media.",
        "info": info,
    }
    torrent_path.write_bytes(bencode(payload))
    return hashlib.sha1(bencode(info)).digest()


class FixtureState:
    def __init__(self, media_path: Path, torrent_path: Path):
        self.media_path = media_path
        self.torrent_path = torrent_path
        self.info_hash = build_torrent(media_path, torrent_path)
        self.peers: dict[bytes, dict[tuple[str, int], float]] = {}
        self.lock = threading.Lock()

    def announce(self, info_hash: bytes, address: str, port: int, event: str) -> bytes:
        now = time.time()
        with self.lock:
            peers = self.peers.setdefault(info_hash, {})
            expired = [peer for peer, seen in peers.items() if now - seen > 300]
            for peer in expired:
                peers.pop(peer, None)
            identity = (address, port)
            if event == "stopped":
                peers.pop(identity, None)
            else:
                peers[identity] = now
            compact = bytearray()
            for peer_address, peer_port in peers:
                if (peer_address, peer_port) == identity:
                    continue
                try:
                    compact.extend(socket.inet_aton(peer_address))
                    compact.extend(struct.pack("!H", peer_port))
                except OSError:
                    continue
            complete = sum(1 for _ in peers)
        return bencode({"interval": 10, "min interval": 5, "complete": complete, "incomplete": 0, "peers": bytes(compact)})


def raw_query(query: str) -> dict[str, bytes]:
    result: dict[str, bytes] = {}
    for pair in query.split("&"):
        if not pair:
            continue
        key, _, value = pair.partition("=")
        result[unquote_to_bytes(key).decode("utf-8", "replace")] = unquote_to_bytes(value.replace("+", " "))
    return result


def caps_xml() -> str:
    return """<?xml version="1.0" encoding="UTF-8"?>
<caps>
  <server version="1.0" title="Torve Legal Fixture" />
  <limits max="100" default="100" />
  <searching><search available="yes" supportedParams="q" /><movie-search available="yes" supportedParams="q,imdbid,tmdbid" /><tv-search available="yes" supportedParams="q,season,ep,tvdbid" /></searching>
  <categories><category id="2000" name="Movies"><subcat id="2040" name="Movies/HD" /></category><category id="5000" name="TV"><subcat id="5040" name="TV/HD" /></category></categories>
</caps>"""


def search_xml(state: FixtureState, public_base: str) -> str:
    torrent_url = f"{public_base}/download/sample.torrent"
    size = state.media_path.stat().st_size
    guid = "torve-e2e-" + state.info_hash.hex()
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:torznab="http://torznab.com/schemas/2015/feed">
  <channel>
    <title>Torve Legal Fixture</title><description>Generated E2E release</description><link>{public_base}</link>
    <torznab:response offset="0" total="1" />
    <item>
      <title>{RELEASE_TITLE}</title><guid isPermaLink="false">{guid}</guid><link>{torrent_url}</link>
      <pubDate>Sat, 25 Jul 2026 12:00:00 GMT</pubDate><category>Movies/HD</category>
      <enclosure url="{torrent_url}" length="{size}" type="application/x-bittorrent" />
      <torznab:attr name="category" value="2000" /><torznab:attr name="category" value="2040" />
      <torznab:attr name="size" value="{size}" /><torznab:attr name="seeders" value="1" /><torznab:attr name="peers" value="1" />
      <torznab:attr name="downloadvolumefactor" value="0" /><torznab:attr name="uploadvolumefactor" value="1" />
    </item>
  </channel>
</rss>"""


class FixtureHandler(BaseHTTPRequestHandler):
    server_version = "TorveFixture/1.0"

    @property
    def state(self) -> FixtureState:
        return self.server.state  # type: ignore[attr-defined]

    def do_GET(self):
        parsed = urlsplit(self.path)
        if parsed.path == "/health":
            self._send(200, b"ok", "text/plain")
            return
        if parsed.path == "/announce":
            query = raw_query(parsed.query)
            info_hash = query.get("info_hash", b"")
            port = int(query.get("port", b"0") or b"0")
            event = query.get("event", b"").decode("ascii", "ignore")
            payload = self.state.announce(info_hash, self.client_address[0], port, event)
            self._send(200, payload, "text/plain")
            return
        if parsed.path == "/download/sample.torrent":
            self.send_response(200)
            self.send_header("Content-Type", "application/x-bittorrent")
            self.send_header("Content-Length", str(self.state.torrent_path.stat().st_size))
            self.send_header("Content-Disposition", 'attachment; filename="torve-e2e-sample.torrent"')
            self.end_headers()
            self.wfile.write(self.state.torrent_path.read_bytes())
            return
        if parsed.path == "/api":
            query = raw_query(parsed.query)
            action = query.get("t", b"search").decode("utf-8", "replace")
            public_base = "http://fixture:8080"
            xml = caps_xml() if action == "caps" else search_xml(self.state, public_base)
            self._send(200, xml.encode("utf-8"), "application/xml; charset=utf-8")
            return
        self._send(404, b"not found", "text/plain")

    def log_message(self, fmt, *args):
        if self.path.startswith("/health"):
            return
        super().log_message(fmt, *args)

    def _send(self, status: int, payload: bytes, content_type: str):
        self.send_response(status)
        self.send_header("Content-Type", content_type)
        self.send_header("Content-Length", str(len(payload)))
        self.end_headers()
        self.wfile.write(payload)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--media", default=f"/fixture/{TORRENT_NAME}")
    parser.add_argument("--torrent", default="/fixture/sample.torrent")
    parser.add_argument("--port", type=int, default=8080)
    args = parser.parse_args()
    media_path = Path(args.media)
    deadline = time.time() + 180
    while not media_path.exists() and time.time() < deadline:
        time.sleep(1)
    if not media_path.exists():
        raise SystemExit(f"Generated media did not appear at {media_path}")
    state = FixtureState(media_path, Path(args.torrent))
    server = ThreadingHTTPServer(("0.0.0.0", args.port), FixtureHandler)
    server.state = state  # type: ignore[attr-defined]
    server.serve_forever()


if __name__ == "__main__":
    main()
